export const CAMPUSES = 'CAMPUSES'
export const STUDENTS = 'STUDENTS'
export const ERROR = 'ERROR'
export const LOADING = 'LOADING'
export const SINGLE_CAMPUS = 'SINGLE_CAMPUS'
export const SINGLE_STUDENT = 'SINGLE_STUDENT'